const GLOBALTYPES = {
    PAGE: {
        SET_DYNAMIC_PAGE: 'SET_DYNAMIC_PAGE',
        GET_DYNAMIC_PAGES: 'GET_DYNAMIC_PAGES',
        DYNAMIC_PAGE_INFO: 'DYNAMIC_PAGE_INFO'
    }
};

export default GLOBALTYPES;
